spacep/spacep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

 
urlpatterns = [

path('admin/', admin.site.urls),
path("",include("test1.urls"))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spacep/test1/urls.py


from django.urls import path, include
from . import views

app_name = "test1"
urlpatterns = [


path("",views.Index.as_view()),
path("details/<int:pk>/",views.detailsDetailView.as_view(), name='details'),
path("help",views.Index2.as_view()),

]

spacep/test1/models.py
from django.db import models
import os.path

class Imges(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField()
    desc = models.TextField()
    code = models.TextField(default="code")



spacep/test2/models.py
from django.db import models

# Create your models here.

spacep/test1/views.py
from re import template
from django.views.generic import View, TemplateView, ListView, DetailView
from django.shortcuts import render
from . models import Imges
class Index(ListView):
 
 template_name = 'index.html'


 model = Imges


class Index2(ListView):
 
 template_name = 'help.html'


 model = Imges

class detailsDetailView(DetailView):
    template_name="details.html"
    model = Imges
    context_object_name = 'Imges'

spacep/test2/views.py
from django.shortcuts import render

# Create your views here.

spacep/templates/details.html

{% load static %}
<link rel="stylesheet" href="{%static 'details.css'%}"/>
<link rel="stylesheet" href="{%static 'button.css'%}"/>
<link rel="stylesheet" href="{%static 'projects.css'%}"/>

<link rel="stylesheet" href="{%static 'notwrk.js'%}"/>

<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@300&display=swap" rel="stylesheet"> 
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Changa&display=swap" rel="stylesheet"> 
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@600&display=swap" rel="stylesheet"> 

<!--
  <center> <h1></h1></center> 
-->
<header>

  <a href="http://127.0.0.1:8000/" class="logo"style="font-family: 'El Messiri', sans-serif;font-size:40px;">اكواد</a>
  <nav class="navbar">
  <a href="http://127.0.0.1:8000/help">مساعده</a>

  </nav>

</header>



  
<div class="container">
  <div href="" class="label" style=" padding: 5%; font-size: 30px;font-family: 'Changa', sans-serif;">
    <a href="https://wa.me/?text=لتحصل على خصم {{Imges.title}} جرب كود http://127.0.0.1:8000/details/7/"><i class="fa-brands fa-whatsapp" style="text-decoration: none;color:black; "></i></a>
  </div>

  <div class="label" style=" padding: 5%; font-size: 30px;font-family: 'Changa', sans-serif;">
  {{Imges.title}}<br/>{{Imges.desc}}<br/>  أنسخ الكود
  </div>
  <div class="copy-text">
    <input type="text"class="text" value="{{Imges.code}}" autocomplete="off">
    <button>
      <i class="fa fa-clone"></i>
    </button>
  </div>
</div>


<div class="con" href="#">
  <span class="buttons" ></span>
 

  
</div>


<!--
<section>
<form
  action="https://formspree.io/f/xgerkbgr"
  method="POST"
>
<div class="container"></div>
  <label>
    Your email:
    <input type="email" name="email">
  </label>
  <label>
    Your message:
    <textarea name="message"></textarea>
  </label>

  <button type="submit">Send</button>
</form></section>
-->

<div class="con" href="#">

<script>let copyText=document.querySelector(".copy-text");
  copyText.querySelector("button").addEventListener("click",function(){
    let input=copyText.querySelector("input.text");
    input.select();
    document.execCommand("copy");
    copyText.classList.add("active");
    window.getSelection().removeA11Ranges();
    setTimeout(function(){
      copyText.classList.remove("active");
    },2500);
  });</script>
  
  <footer class="footer">
  <p> Copyright @<span>akwad</span></p>
</footer>

spacep/templates/help.html

{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@600&display=swap" rel="stylesheet"> 
<link rel="stylesheet" href="{%static 'help.css'%}"/>
<header>

  <a  href="http://127.0.0.1:8000/" class="logo"style="font-family: 'El Messiri', sans-serif;font-size:40px;">اكواد</a>
  <nav class="navbar">
  <a href="#contact">مساعده</a>

  </nav>
</header>
<section>
    <div class="container">
        <form
        action="https://formspree.io/f/xgerkbgr"
        method="POST"
      >
  
        <div class="form-group">
          <label for="firstName"> الاسم</label>
          <input type="text" id="firstName" name="firstName">
        </div>
  
        <div class="form-group">
          <label for="latsName">نوع المشكله</label>
          <input type="text" id="lastName" name="lastName">
        </div>
  
        <div class="form-group">
          <label for="email">البريد الالكتروني</label>
          <input type="email" id="email" name="email">
        </div>
  
        <div class="form-group">
          <label for="massage">شرح المشكله</label>
          <textarea name="massage" id="massage" cols="30" rows="10"></textarea>
        </div>
  
        <button type="submit">ارسال</button>
      </form>
    </div>
    <div id="status"></div>
  </section>

spacep/templates/index.html
{% load static %}
<link rel="stylesheet" href="{%static 'style.css'%}"/>
<link rel="stylesheet" href="{%static 'footer.css'%}"/>
<link rel="stylesheet" href="{%static 'projects.css'%}"/>
<link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@600&display=swap" rel="stylesheet"> 
<body>
    <header>

        <a  href="http://127.0.0.1:8000/" class="logo"style="font-family: 'El Messiri', sans-serif;font-size:40px;">اكواد</a>
        <nav class="navbar">
        <a href="http://127.0.0.1:8000/help">مساعده</a>
     
        </nav>
    </header>
    
   <!-- <article>
    <a href="#"class="image"><img src="{{ Imges.image.url }}" alt="img" /></a>
    <h3>{{ Imges.title }}</h3>
    <p>{{Imges.desc}}</p>
    <ul class="actions">
        <li><a href="#" class="button">More</a></li>
    </ul></article>-->


 <div class="container">
<section class="projects"id="projects">
  

    <div class="content">{%for Imges in object_list%}
         <div class="project-card">
              <div class="project-image">
                 <a href="#"> <img src="{{ Imges.image.url }}" /></a>
              </div>
             <div class="project-info">
                <h2 class="title" >{{Imges.title}}</h2>
            <strong class="project-title"><span>{{Imges.desc}}</span>
                <br/>
            <a href="{% url 'test1:details' Imges.id %}" class="datels">more</a>
            </strong>
            </div>
         </div>
   {%endfor%} </div>
</section></div>
<footer class="footer">
    <p> Copyright @<span>akwad</span></p>
</footer>
</body>